// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem.proto

package filesystem;

public interface DownloadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.DownloadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>string content_base64 = 2;</code>
   * @return The contentBase64.
   */
  java.lang.String getContentBase64();
  /**
   * <code>string content_base64 = 2;</code>
   * @return The bytes for contentBase64.
   */
  com.google.protobuf.ByteString
      getContentBase64Bytes();

  /**
   * <code>int64 filesize = 3;</code>
   * @return The filesize.
   */
  long getFilesize();

  /**
   * <code>string file_type = 4;</code>
   * @return The fileType.
   */
  java.lang.String getFileType();
  /**
   * <code>string file_type = 4;</code>
   * @return The bytes for fileType.
   */
  com.google.protobuf.ByteString
      getFileTypeBytes();
}
