// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem.proto

package filesystem;

public final class Filesystem {
  private Filesystem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_UploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_UploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_DirectoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_DirectoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_SubdirectoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_SubdirectoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_RenameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_RenameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_MoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_MoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_NodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_NodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_NodeStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_NodeStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020filesystem.proto\022\nfilesystem\"E\n\rUpload" +
      "Request\022\020\n\010filename\030\001 \001(\t\022\021\n\tdirectory\030\002" +
      " \001(\t\022\017\n\007content\030\003 \001(\014\" \n\020DirectoryReques" +
      "t\022\014\n\004path\030\001 \001(\t\"J\n\023SubdirectoryRequest\022\030" +
      "\n\020parent_directory\030\001 \001(\t\022\031\n\021subdirectory" +
      "_name\030\002 \001(\t\"3\n\rRenameRequest\022\020\n\010old_name" +
      "\030\001 \001(\t\022\020\n\010new_name\030\002 \001(\t\"\035\n\rDeleteReques" +
      "t\022\014\n\004path\030\001 \001(\t\"<\n\013MoveRequest\022\023\n\013source" +
      "_path\030\001 \001(\t\022\030\n\020destination_path\030\002 \001(\t\"\033\n" +
      "\010Response\022\017\n\007message\030\001 \001(\t\"\035\n\014ListRespon" +
      "se\022\r\n\005files\030\001 \003(\t\"+\n\010NodeInfo\022\017\n\007address" +
      "\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\"-\n\nNodeStatus\022\017\n\007" +
      "address\030\001 \001(\t\022\016\n\006status\030\002 \001(\t2\344\003\n\021FileSy" +
      "stemService\022=\n\nUploadFile\022\031.filesystem.U" +
      "ploadRequest\032\024.filesystem.Response\022E\n\017Cr" +
      "eateDirectory\022\034.filesystem.DirectoryRequ" +
      "est\032\024.filesystem.Response\022K\n\022CreateSubdi" +
      "rectory\022\037.filesystem.SubdirectoryRequest" +
      "\032\024.filesystem.Response\022=\n\nRenameFile\022\031.f" +
      "ilesystem.RenameRequest\032\024.filesystem.Res" +
      "ponse\022=\n\nDeleteFile\022\031.filesystem.DeleteR" +
      "equest\032\024.filesystem.Response\022C\n\tListFile" +
      "s\022\034.filesystem.DirectoryRequest\032\030.filesy" +
      "stem.ListResponse\0229\n\010MoveFile\022\027.filesyst" +
      "em.MoveRequest\032\024.filesystem.Response2\207\001\n" +
      "\013NodeService\022:\n\014RegisterNode\022\024.filesyste" +
      "m.NodeInfo\032\024.filesystem.Response\022<\n\014Repo" +
      "rtStatus\022\026.filesystem.NodeStatus\032\024.files" +
      "ystem.ResponseB \n\nfilesystemP\001Z\020proto/fi" +
      "lesystemb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_filesystem_UploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_filesystem_UploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_UploadRequest_descriptor,
        new java.lang.String[] { "Filename", "Directory", "Content", });
    internal_static_filesystem_DirectoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_filesystem_DirectoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_DirectoryRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_filesystem_SubdirectoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_filesystem_SubdirectoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_SubdirectoryRequest_descriptor,
        new java.lang.String[] { "ParentDirectory", "SubdirectoryName", });
    internal_static_filesystem_RenameRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_filesystem_RenameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_RenameRequest_descriptor,
        new java.lang.String[] { "OldName", "NewName", });
    internal_static_filesystem_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_filesystem_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_DeleteRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_filesystem_MoveRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_filesystem_MoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_MoveRequest_descriptor,
        new java.lang.String[] { "SourcePath", "DestinationPath", });
    internal_static_filesystem_Response_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_filesystem_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_Response_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_filesystem_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_filesystem_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_ListResponse_descriptor,
        new java.lang.String[] { "Files", });
    internal_static_filesystem_NodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_filesystem_NodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_NodeInfo_descriptor,
        new java.lang.String[] { "Address", "Status", });
    internal_static_filesystem_NodeStatus_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_filesystem_NodeStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_NodeStatus_descriptor,
        new java.lang.String[] { "Address", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
