// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem.proto

package filesystem;

public final class Filesystem {
  private Filesystem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_UploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_UploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_DirectoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_DirectoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_SubdirectoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_SubdirectoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_RenameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_RenameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_MoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_MoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_ListAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_ListAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_NodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_NodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_NodeStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_NodeStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020filesystem.proto\022\nfilesystem\"\\\n\rUpload" +
      "Request\022\020\n\010filename\030\001 \001(\t\022\021\n\tdirectory\030\002" +
      " \001(\t\022\017\n\007content\030\003 \001(\014\022\025\n\rcontentBase64\030\004" +
      " \001(\t\" \n\020DirectoryRequest\022\014\n\004path\030\001 \001(\t\"J" +
      "\n\023SubdirectoryRequest\022\030\n\020parent_director" +
      "y\030\001 \001(\t\022\031\n\021subdirectory_name\030\002 \001(\t\"3\n\rRe" +
      "nameRequest\022\020\n\010old_name\030\001 \001(\t\022\020\n\010new_nam" +
      "e\030\002 \001(\t\"\035\n\rDeleteRequest\022\014\n\004path\030\001 \001(\t\"<" +
      "\n\013MoveRequest\022\023\n\013source_path\030\001 \001(\t\022\030\n\020de" +
      "stination_path\030\002 \001(\t\"w\n\010Response\022\017\n\007mess" +
      "age\030\001 \001(\t\022\021\n\tfile_path\030\002 \001(\t\022\021\n\tfile_nam" +
      "e\030\003 \001(\t\022\021\n\tfile_size\030\004 \001(\003\022\021\n\tfile_type\030" +
      "\005 \001(\t\022\016\n\006nodeId\030\006 \001(\t\"\035\n\014ListResponse\022\r\n" +
      "\005files\030\001 \003(\t\"5\n\017ListAllResponse\022\r\n\005files" +
      "\030\001 \003(\t\022\023\n\013directories\030\002 \003(\t\"+\n\010NodeInfo\022" +
      "\017\n\007address\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\"-\n\nNode" +
      "Status\022\017\n\007address\030\001 \001(\t\022\016\n\006status\030\002 \001(\t2" +
      "\252\004\n\021FileSystemService\022=\n\nUploadFile\022\031.fi" +
      "lesystem.UploadRequest\032\024.filesystem.Resp" +
      "onse\022E\n\017CreateDirectory\022\034.filesystem.Dir" +
      "ectoryRequest\032\024.filesystem.Response\022K\n\022C" +
      "reateSubdirectory\022\037.filesystem.Subdirect" +
      "oryRequest\032\024.filesystem.Response\022=\n\nRena" +
      "meFile\022\031.filesystem.RenameRequest\032\024.file" +
      "system.Response\022=\n\nDeleteFile\022\031.filesyst" +
      "em.DeleteRequest\032\024.filesystem.Response\022C" +
      "\n\tListFiles\022\034.filesystem.DirectoryReques" +
      "t\032\030.filesystem.ListResponse\0229\n\010MoveFile\022" +
      "\027.filesystem.MoveRequest\032\024.filesystem.Re" +
      "sponse\022D\n\007ListAll\022\034.filesystem.Directory" +
      "Request\032\033.filesystem.ListAllResponse2\207\001\n" +
      "\013NodeService\022:\n\014RegisterNode\022\024.filesyste" +
      "m.NodeInfo\032\024.filesystem.Response\022<\n\014Repo" +
      "rtStatus\022\026.filesystem.NodeStatus\032\024.files" +
      "ystem.ResponseB \n\nfilesystemP\001Z\020proto/fi" +
      "lesystemb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_filesystem_UploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_filesystem_UploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_UploadRequest_descriptor,
        new java.lang.String[] { "Filename", "Directory", "Content", "ContentBase64", });
    internal_static_filesystem_DirectoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_filesystem_DirectoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_DirectoryRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_filesystem_SubdirectoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_filesystem_SubdirectoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_SubdirectoryRequest_descriptor,
        new java.lang.String[] { "ParentDirectory", "SubdirectoryName", });
    internal_static_filesystem_RenameRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_filesystem_RenameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_RenameRequest_descriptor,
        new java.lang.String[] { "OldName", "NewName", });
    internal_static_filesystem_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_filesystem_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_DeleteRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_filesystem_MoveRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_filesystem_MoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_MoveRequest_descriptor,
        new java.lang.String[] { "SourcePath", "DestinationPath", });
    internal_static_filesystem_Response_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_filesystem_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_Response_descriptor,
        new java.lang.String[] { "Message", "FilePath", "FileName", "FileSize", "FileType", "NodeId", });
    internal_static_filesystem_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_filesystem_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_ListResponse_descriptor,
        new java.lang.String[] { "Files", });
    internal_static_filesystem_ListAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_filesystem_ListAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_ListAllResponse_descriptor,
        new java.lang.String[] { "Files", "Directories", });
    internal_static_filesystem_NodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_filesystem_NodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_NodeInfo_descriptor,
        new java.lang.String[] { "Address", "Status", });
    internal_static_filesystem_NodeStatus_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_filesystem_NodeStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_NodeStatus_descriptor,
        new java.lang.String[] { "Address", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
