// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem.proto

package filesystem;

/**
 * Protobuf type {@code filesystem.ListAllResponse}
 */
public final class ListAllResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:filesystem.ListAllResponse)
    ListAllResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListAllResponse.newBuilder() to construct.
  private ListAllResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListAllResponse() {
    files_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    directories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListAllResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return filesystem.Filesystem.internal_static_filesystem_ListAllResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return filesystem.Filesystem.internal_static_filesystem_ListAllResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            filesystem.ListAllResponse.class, filesystem.ListAllResponse.Builder.class);
  }

  public static final int FILES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList files_;
  /**
   * <code>repeated string files = 1;</code>
   * @return A list containing the files.
   */
  public com.google.protobuf.ProtocolStringList
      getFilesList() {
    return files_;
  }
  /**
   * <code>repeated string files = 1;</code>
   * @return The count of files.
   */
  public int getFilesCount() {
    return files_.size();
  }
  /**
   * <code>repeated string files = 1;</code>
   * @param index The index of the element to return.
   * @return The files at the given index.
   */
  public java.lang.String getFiles(int index) {
    return files_.get(index);
  }
  /**
   * <code>repeated string files = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the files at the given index.
   */
  public com.google.protobuf.ByteString
      getFilesBytes(int index) {
    return files_.getByteString(index);
  }

  public static final int DIRECTORIES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList directories_;
  /**
   * <code>repeated string directories = 2;</code>
   * @return A list containing the directories.
   */
  public com.google.protobuf.ProtocolStringList
      getDirectoriesList() {
    return directories_;
  }
  /**
   * <code>repeated string directories = 2;</code>
   * @return The count of directories.
   */
  public int getDirectoriesCount() {
    return directories_.size();
  }
  /**
   * <code>repeated string directories = 2;</code>
   * @param index The index of the element to return.
   * @return The directories at the given index.
   */
  public java.lang.String getDirectories(int index) {
    return directories_.get(index);
  }
  /**
   * <code>repeated string directories = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the directories at the given index.
   */
  public com.google.protobuf.ByteString
      getDirectoriesBytes(int index) {
    return directories_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < files_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, files_.getRaw(i));
    }
    for (int i = 0; i < directories_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, directories_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < files_.size(); i++) {
        dataSize += computeStringSizeNoTag(files_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFilesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < directories_.size(); i++) {
        dataSize += computeStringSizeNoTag(directories_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDirectoriesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof filesystem.ListAllResponse)) {
      return super.equals(obj);
    }
    filesystem.ListAllResponse other = (filesystem.ListAllResponse) obj;

    if (!getFilesList()
        .equals(other.getFilesList())) return false;
    if (!getDirectoriesList()
        .equals(other.getDirectoriesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFilesCount() > 0) {
      hash = (37 * hash) + FILES_FIELD_NUMBER;
      hash = (53 * hash) + getFilesList().hashCode();
    }
    if (getDirectoriesCount() > 0) {
      hash = (37 * hash) + DIRECTORIES_FIELD_NUMBER;
      hash = (53 * hash) + getDirectoriesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static filesystem.ListAllResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static filesystem.ListAllResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static filesystem.ListAllResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static filesystem.ListAllResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static filesystem.ListAllResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static filesystem.ListAllResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static filesystem.ListAllResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static filesystem.ListAllResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static filesystem.ListAllResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static filesystem.ListAllResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static filesystem.ListAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static filesystem.ListAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(filesystem.ListAllResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code filesystem.ListAllResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:filesystem.ListAllResponse)
      filesystem.ListAllResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return filesystem.Filesystem.internal_static_filesystem_ListAllResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return filesystem.Filesystem.internal_static_filesystem_ListAllResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              filesystem.ListAllResponse.class, filesystem.ListAllResponse.Builder.class);
    }

    // Construct using filesystem.ListAllResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      files_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      directories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return filesystem.Filesystem.internal_static_filesystem_ListAllResponse_descriptor;
    }

    @java.lang.Override
    public filesystem.ListAllResponse getDefaultInstanceForType() {
      return filesystem.ListAllResponse.getDefaultInstance();
    }

    @java.lang.Override
    public filesystem.ListAllResponse build() {
      filesystem.ListAllResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public filesystem.ListAllResponse buildPartial() {
      filesystem.ListAllResponse result = new filesystem.ListAllResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(filesystem.ListAllResponse result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        files_ = files_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.files_ = files_;
      if (((bitField0_ & 0x00000002) != 0)) {
        directories_ = directories_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.directories_ = directories_;
    }

    private void buildPartial0(filesystem.ListAllResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof filesystem.ListAllResponse) {
        return mergeFrom((filesystem.ListAllResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(filesystem.ListAllResponse other) {
      if (other == filesystem.ListAllResponse.getDefaultInstance()) return this;
      if (!other.files_.isEmpty()) {
        if (files_.isEmpty()) {
          files_ = other.files_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFilesIsMutable();
          files_.addAll(other.files_);
        }
        onChanged();
      }
      if (!other.directories_.isEmpty()) {
        if (directories_.isEmpty()) {
          directories_ = other.directories_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureDirectoriesIsMutable();
          directories_.addAll(other.directories_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFilesIsMutable();
              files_.add(s);
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureDirectoriesIsMutable();
              directories_.add(s);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList files_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFilesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        files_ = new com.google.protobuf.LazyStringArrayList(files_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string files = 1;</code>
     * @return A list containing the files.
     */
    public com.google.protobuf.ProtocolStringList
        getFilesList() {
      return files_.getUnmodifiableView();
    }
    /**
     * <code>repeated string files = 1;</code>
     * @return The count of files.
     */
    public int getFilesCount() {
      return files_.size();
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param index The index of the element to return.
     * @return The files at the given index.
     */
    public java.lang.String getFiles(int index) {
      return files_.get(index);
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the files at the given index.
     */
    public com.google.protobuf.ByteString
        getFilesBytes(int index) {
      return files_.getByteString(index);
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param index The index to set the value at.
     * @param value The files to set.
     * @return This builder for chaining.
     */
    public Builder setFiles(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFilesIsMutable();
      files_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param value The files to add.
     * @return This builder for chaining.
     */
    public Builder addFiles(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFilesIsMutable();
      files_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param values The files to add.
     * @return This builder for chaining.
     */
    public Builder addAllFiles(
        java.lang.Iterable<java.lang.String> values) {
      ensureFilesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, files_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFiles() {
      files_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param value The bytes of the files to add.
     * @return This builder for chaining.
     */
    public Builder addFilesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFilesIsMutable();
      files_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList directories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDirectoriesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        directories_ = new com.google.protobuf.LazyStringArrayList(directories_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string directories = 2;</code>
     * @return A list containing the directories.
     */
    public com.google.protobuf.ProtocolStringList
        getDirectoriesList() {
      return directories_.getUnmodifiableView();
    }
    /**
     * <code>repeated string directories = 2;</code>
     * @return The count of directories.
     */
    public int getDirectoriesCount() {
      return directories_.size();
    }
    /**
     * <code>repeated string directories = 2;</code>
     * @param index The index of the element to return.
     * @return The directories at the given index.
     */
    public java.lang.String getDirectories(int index) {
      return directories_.get(index);
    }
    /**
     * <code>repeated string directories = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the directories at the given index.
     */
    public com.google.protobuf.ByteString
        getDirectoriesBytes(int index) {
      return directories_.getByteString(index);
    }
    /**
     * <code>repeated string directories = 2;</code>
     * @param index The index to set the value at.
     * @param value The directories to set.
     * @return This builder for chaining.
     */
    public Builder setDirectories(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDirectoriesIsMutable();
      directories_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directories = 2;</code>
     * @param value The directories to add.
     * @return This builder for chaining.
     */
    public Builder addDirectories(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDirectoriesIsMutable();
      directories_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directories = 2;</code>
     * @param values The directories to add.
     * @return This builder for chaining.
     */
    public Builder addAllDirectories(
        java.lang.Iterable<java.lang.String> values) {
      ensureDirectoriesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, directories_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directories = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirectories() {
      directories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directories = 2;</code>
     * @param value The bytes of the directories to add.
     * @return This builder for chaining.
     */
    public Builder addDirectoriesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureDirectoriesIsMutable();
      directories_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:filesystem.ListAllResponse)
  }

  // @@protoc_insertion_point(class_scope:filesystem.ListAllResponse)
  private static final filesystem.ListAllResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new filesystem.ListAllResponse();
  }

  public static filesystem.ListAllResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListAllResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListAllResponse>() {
    @java.lang.Override
    public ListAllResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListAllResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListAllResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public filesystem.ListAllResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

