// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem.proto

package filesystem;

public interface ListAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.ListAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string files = 1;</code>
   * @return A list containing the files.
   */
  java.util.List<java.lang.String>
      getFilesList();
  /**
   * <code>repeated string files = 1;</code>
   * @return The count of files.
   */
  int getFilesCount();
  /**
   * <code>repeated string files = 1;</code>
   * @param index The index of the element to return.
   * @return The files at the given index.
   */
  java.lang.String getFiles(int index);
  /**
   * <code>repeated string files = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the files at the given index.
   */
  com.google.protobuf.ByteString
      getFilesBytes(int index);

  /**
   * <code>repeated string directories = 2;</code>
   * @return A list containing the directories.
   */
  java.util.List<java.lang.String>
      getDirectoriesList();
  /**
   * <code>repeated string directories = 2;</code>
   * @return The count of directories.
   */
  int getDirectoriesCount();
  /**
   * <code>repeated string directories = 2;</code>
   * @param index The index of the element to return.
   * @return The directories at the given index.
   */
  java.lang.String getDirectories(int index);
  /**
   * <code>repeated string directories = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the directories at the given index.
   */
  com.google.protobuf.ByteString
      getDirectoriesBytes(int index);
}
