// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem.proto

package filesystem;

public interface MoveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.MoveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source_path = 1;</code>
   * @return The sourcePath.
   */
  java.lang.String getSourcePath();
  /**
   * <code>string source_path = 1;</code>
   * @return The bytes for sourcePath.
   */
  com.google.protobuf.ByteString
      getSourcePathBytes();

  /**
   * <code>string destination_path = 2;</code>
   * @return The destinationPath.
   */
  java.lang.String getDestinationPath();
  /**
   * <code>string destination_path = 2;</code>
   * @return The bytes for destinationPath.
   */
  com.google.protobuf.ByteString
      getDestinationPathBytes();
}
