// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem.proto

package filesystem;

public interface NodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.NodeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Dirección del nodo (por ejemplo, "ip:puerto")
   * </pre>
   *
   * <code>string address = 1;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <pre>
   * Dirección del nodo (por ejemplo, "ip:puerto")
   * </pre>
   *
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <pre>
   * Estado inicial (por ejemplo, "activo")
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * Estado inicial (por ejemplo, "activo")
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
