// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem.proto

package filesystem;

public interface RenameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.RenameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string old_name = 1;</code>
   * @return The oldName.
   */
  java.lang.String getOldName();
  /**
   * <code>string old_name = 1;</code>
   * @return The bytes for oldName.
   */
  com.google.protobuf.ByteString
      getOldNameBytes();

  /**
   * <code>string new_name = 2;</code>
   * @return The newName.
   */
  java.lang.String getNewName();
  /**
   * <code>string new_name = 2;</code>
   * @return The bytes for newName.
   */
  com.google.protobuf.ByteString
      getNewNameBytes();
}
