// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem.proto

package filesystem;

/**
 * Protobuf type {@code filesystem.SubdirectoryRequest}
 */
public final class SubdirectoryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:filesystem.SubdirectoryRequest)
    SubdirectoryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubdirectoryRequest.newBuilder() to construct.
  private SubdirectoryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubdirectoryRequest() {
    parentDirectory_ = "";
    subdirectoryName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubdirectoryRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return filesystem.Filesystem.internal_static_filesystem_SubdirectoryRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return filesystem.Filesystem.internal_static_filesystem_SubdirectoryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            filesystem.SubdirectoryRequest.class, filesystem.SubdirectoryRequest.Builder.class);
  }

  public static final int PARENT_DIRECTORY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentDirectory_ = "";
  /**
   * <code>string parent_directory = 1;</code>
   * @return The parentDirectory.
   */
  @java.lang.Override
  public java.lang.String getParentDirectory() {
    java.lang.Object ref = parentDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>string parent_directory = 1;</code>
   * @return The bytes for parentDirectory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentDirectoryBytes() {
    java.lang.Object ref = parentDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBDIRECTORY_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object subdirectoryName_ = "";
  /**
   * <code>string subdirectory_name = 2;</code>
   * @return The subdirectoryName.
   */
  @java.lang.Override
  public java.lang.String getSubdirectoryName() {
    java.lang.Object ref = subdirectoryName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subdirectoryName_ = s;
      return s;
    }
  }
  /**
   * <code>string subdirectory_name = 2;</code>
   * @return The bytes for subdirectoryName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubdirectoryNameBytes() {
    java.lang.Object ref = subdirectoryName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subdirectoryName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentDirectory_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, parentDirectory_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subdirectoryName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subdirectoryName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentDirectory_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, parentDirectory_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subdirectoryName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subdirectoryName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof filesystem.SubdirectoryRequest)) {
      return super.equals(obj);
    }
    filesystem.SubdirectoryRequest other = (filesystem.SubdirectoryRequest) obj;

    if (!getParentDirectory()
        .equals(other.getParentDirectory())) return false;
    if (!getSubdirectoryName()
        .equals(other.getSubdirectoryName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARENT_DIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getParentDirectory().hashCode();
    hash = (37 * hash) + SUBDIRECTORY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getSubdirectoryName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static filesystem.SubdirectoryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static filesystem.SubdirectoryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static filesystem.SubdirectoryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static filesystem.SubdirectoryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static filesystem.SubdirectoryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static filesystem.SubdirectoryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static filesystem.SubdirectoryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static filesystem.SubdirectoryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static filesystem.SubdirectoryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static filesystem.SubdirectoryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static filesystem.SubdirectoryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static filesystem.SubdirectoryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(filesystem.SubdirectoryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code filesystem.SubdirectoryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:filesystem.SubdirectoryRequest)
      filesystem.SubdirectoryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return filesystem.Filesystem.internal_static_filesystem_SubdirectoryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return filesystem.Filesystem.internal_static_filesystem_SubdirectoryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              filesystem.SubdirectoryRequest.class, filesystem.SubdirectoryRequest.Builder.class);
    }

    // Construct using filesystem.SubdirectoryRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      parentDirectory_ = "";
      subdirectoryName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return filesystem.Filesystem.internal_static_filesystem_SubdirectoryRequest_descriptor;
    }

    @java.lang.Override
    public filesystem.SubdirectoryRequest getDefaultInstanceForType() {
      return filesystem.SubdirectoryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public filesystem.SubdirectoryRequest build() {
      filesystem.SubdirectoryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public filesystem.SubdirectoryRequest buildPartial() {
      filesystem.SubdirectoryRequest result = new filesystem.SubdirectoryRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(filesystem.SubdirectoryRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.parentDirectory_ = parentDirectory_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.subdirectoryName_ = subdirectoryName_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof filesystem.SubdirectoryRequest) {
        return mergeFrom((filesystem.SubdirectoryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(filesystem.SubdirectoryRequest other) {
      if (other == filesystem.SubdirectoryRequest.getDefaultInstance()) return this;
      if (!other.getParentDirectory().isEmpty()) {
        parentDirectory_ = other.parentDirectory_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSubdirectoryName().isEmpty()) {
        subdirectoryName_ = other.subdirectoryName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              parentDirectory_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              subdirectoryName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object parentDirectory_ = "";
    /**
     * <code>string parent_directory = 1;</code>
     * @return The parentDirectory.
     */
    public java.lang.String getParentDirectory() {
      java.lang.Object ref = parentDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parent_directory = 1;</code>
     * @return The bytes for parentDirectory.
     */
    public com.google.protobuf.ByteString
        getParentDirectoryBytes() {
      java.lang.Object ref = parentDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parent_directory = 1;</code>
     * @param value The parentDirectory to set.
     * @return This builder for chaining.
     */
    public Builder setParentDirectory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentDirectory_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string parent_directory = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentDirectory() {
      parentDirectory_ = getDefaultInstance().getParentDirectory();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string parent_directory = 1;</code>
     * @param value The bytes for parentDirectory to set.
     * @return This builder for chaining.
     */
    public Builder setParentDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentDirectory_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object subdirectoryName_ = "";
    /**
     * <code>string subdirectory_name = 2;</code>
     * @return The subdirectoryName.
     */
    public java.lang.String getSubdirectoryName() {
      java.lang.Object ref = subdirectoryName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subdirectoryName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subdirectory_name = 2;</code>
     * @return The bytes for subdirectoryName.
     */
    public com.google.protobuf.ByteString
        getSubdirectoryNameBytes() {
      java.lang.Object ref = subdirectoryName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subdirectoryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subdirectory_name = 2;</code>
     * @param value The subdirectoryName to set.
     * @return This builder for chaining.
     */
    public Builder setSubdirectoryName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      subdirectoryName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string subdirectory_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubdirectoryName() {
      subdirectoryName_ = getDefaultInstance().getSubdirectoryName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string subdirectory_name = 2;</code>
     * @param value The bytes for subdirectoryName to set.
     * @return This builder for chaining.
     */
    public Builder setSubdirectoryNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      subdirectoryName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:filesystem.SubdirectoryRequest)
  }

  // @@protoc_insertion_point(class_scope:filesystem.SubdirectoryRequest)
  private static final filesystem.SubdirectoryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new filesystem.SubdirectoryRequest();
  }

  public static filesystem.SubdirectoryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubdirectoryRequest>
      PARSER = new com.google.protobuf.AbstractParser<SubdirectoryRequest>() {
    @java.lang.Override
    public SubdirectoryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubdirectoryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubdirectoryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public filesystem.SubdirectoryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

