// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filesystem.proto

package filesystem;

public interface SubdirectoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.SubdirectoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string parent_directory = 1;</code>
   * @return The parentDirectory.
   */
  java.lang.String getParentDirectory();
  /**
   * <code>string parent_directory = 1;</code>
   * @return The bytes for parentDirectory.
   */
  com.google.protobuf.ByteString
      getParentDirectoryBytes();

  /**
   * <code>string subdirectory_name = 2;</code>
   * @return The subdirectoryName.
   */
  java.lang.String getSubdirectoryName();
  /**
   * <code>string subdirectory_name = 2;</code>
   * @return The bytes for subdirectoryName.
   */
  com.google.protobuf.ByteString
      getSubdirectoryNameBytes();
}
